# Pipeline de CI/CD com GitHub Actions

name: "Terraform CI/CD Pipeline"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Deploy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar o Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Inicializar Terraform
        run: |
          cd terraform
          terraform init

      - name: Validar Terraform
        run: |
          cd terraform
          terraform validate

      - name: Aplicar Terraform
        run: |
          cd terraform
          terraform apply -auto-approve
